# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('categSimilares', models.ManyToManyField(related_name='_genero_categSimilares_+', to='gestionLibros.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('ultimaFechaIngreso', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('autor', models.CharField(default='Anonimo', max_length=50)),
                ('edicion', models.IntegerField(default=1)),
                ('pubDate', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionLibros.Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('ultimaFechaIngreso', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('editor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionLibros.Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
