# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='categSimilares',
            field=models.ManyToManyField(blank=True, related_name='_genero_categSimilares_+', to='gestionLibros.Genero'),
        ),
    ]
